### ISSUE TITLE
[Android][Bug] 弹幕在 flutter 3.22.0 版本上工作不正确

### ISSUE THREAD

**Issue by Predidit** [xiaoyaocz/flutter_ns_danmaku#3]
非常感谢作者提供给大家一个那么好用的弹幕库。

在升级 `flutter` 到刚刚发布的 `3.22.0` 版本后，弹幕会在进入屏幕约 1 秒后立即消失，此问题只在 Android 平台上出现。实验性的 `impeller` 引擎与默认的 `skia` 渲染引擎均有此问题。

我尝试定位错误，但并没有结果。您能在方便时关注一下这个问题吗。

**Comment by qixiaoo** [comment]
调试了一下，问题的原因似乎是 [这个](https://github.com/flutter/flutter/issues/56537)。

release mode 下的 `key.toString()` 返回的是同一个字符串，导致 `_scrollWidgets` 中始终只有一个组件。
结果就是看起来在播放弹幕时，每当播放当前秒的弹幕时，前一秒的弹幕就会消失。

**Comment by Predidit** [comment]
感谢您的工作。

**Comment by Predidit** [comment]
#4 这个PR似乎存在缺陷，会导致弹幕在运行到屏幕最左边后无法正确地被移除。

**Comment by Predidit** [comment]
我觉得恰当的做法可能是将所有出现 `key.toString();` 方法的地方 ，修改为 `key.hashCode.toString();` 并回滚 #4 中的更改/

**Comment by Predidit** [comment]
我尝试提交了一个PR来解决此问题 #5
